name: Plant Watering ESP8266 CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install PlatformIO
      run: |
        python -m pip install -U pip
        pip install platformio
        pio update
    - name: Compile project
      run: |
        echo -e '#define ssid ""\n#define password ""\n#define writeAPIKey ""\n' > secret.h
        echo -e '#define MQTT_HOST ""\n#define MQTT_PORT 1883\n#define MQTT_USERNAME ""\n#define MQTT_PASSWORD ""\n#define MQTT_TOPIC ""' >> secret.h
        pio run
    - name: Prepare binary
      run: |
        mkdir binary
        cp -v .pio/build/esp12e/firmware.bin binary/PlantWateringESP8266.bin
        pushd binary
        sha256sum * > SHA256SUMS
        popd
    - uses: actions/upload-artifact@v1
      with:
        name: binary-${{ github.sha }}
        path: binary
    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: binary/*
        draft: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
